#! /bin/sh

PROG=`basename $0`
PROGDIR=`dirname $0`

NOW=`date '+%Y%m%d_%H%M%S'`
HOST=`uname -n | cut -d. -f1`

lRC=0

echo "<TABLE  cellSpacing=5 border=1 cellPadding=0>" 
echo "<TBODY>" 

echo "<TR><TD align=center bgcolor=lightyellow>Directory</TD align=center bgcolor=lightyellow><TD align=center bgcolor=lightyellow>Permission</TD align=center bgcolor=lightyellow><TD align=center bgcolor=lightyellow>Owner</TD align=center bgcolor=lightyellow><TD align=center bgcolor=lightyellow>Group</TD align=center bgcolor=lightyellow><TD align=center bgcolor=lightyellow>Status</TD align=center bgcolor=lightyellow></TR>" 

for dir in `cat $PROGDIR/$PROG.$HOST.env`
do
        owner=`stat -c "%A" $dir | cut -c 3-3 `
        group=`stat -c "%A" $dir | cut -c 6-6 `
        world=`stat -c "%A" $dir | cut -c 9-9 `
        perm=`stat -c "%A" $dir `
        ogroup=`stat -c "%G" $dir `
        user=`stat -c "%U" $dir `
 
	if [ $owner == 'w' ] && [ $group == 'w' ] && [ $world == 'w' ]
	then
		echo "<TR><TD align=center bgcolor=ivory>$dir</TD align=center bgcolor=ivory><TD align=center bgcolor=ivory>$perm</TD align=center bgcolor=ivory><TD align=center bgcolor=ivory>$user</TD align=center bgcolor=ivory><TD align=center bgcolor=ivory>$ogroup</TD align=center bgcolor=ivory><TD align=center bgcolor=ivory>SUCCESS</TD align=center bgcolor=ivory></TR>"
	else
		echo "<TR><TD align=center bgcolor=red>$dir</TD align=center bgcolor=red><TD align=center bgcolor=red>$perm</TD align=center bgcolor=red><TD align=center bgcolor=red>$user</TD align=center bgcolor=red><TD align=center bgcolor=red>$ogroup</TD align=center bgcolor=red><TD align=center bgcolor=red>FAILURE</TD align=center bgcolor=red></TR>"
		lRC=`expr $lRC + 1`
	fi
done

echo "</TBODY>" 
echo "</TABLE>" 

if [ $lRC -gt 0 ]; then
   echo "WORLD DIRECTORY PERMS " >> "/tmp/subject_issues"
fi

exit $lRC
