#! /bin/sh

PROG=`basename $0`
PROGDIR=`dirname $0`
TMPDIR=/tmp/
. $PROGDIR/$PROG.env

NOW=`date '+%Y%m%d_%H%M%S'`
HOST=`uname -n | cut -d. -f1`

lRC=0
export lRC

host=`hostname | awk -F '.' '{ print $1 }'`


OUTFILE=$TMPDIR/$PROG.$NOW.$HOST.out
TMPFILE=$TMPDIR/$PROG.$NOW.$HOST.tmp

ps -ef  | awk '{if ($1 != "UID") print $1}' > $OUTFILE

echo "<TABLE  cellSpacing=5 border=1 cellPadding=0>"
echo "<TBODY>"

echo "<TR><TD align=center bgcolor=lightyellow>No.of Processes</TD align=center bgcolor=lightyellow><TD align=center bgcolor=lightyellow>Process Owned By</TD align=center bgcolor=lightyellow></TR>"

for i in `cat $OUTFILE | sort -u`
do
  user_count=`grep $i $OUTFILE | wc -l`
  echo $user_count $i >> $TMPFILE
done

# cat $OUTFILE
# cat $TMPFILE

sort -rn $TMPFILE | { while read user_count user_id
do
	if [ $user_id != "root"  -a  $user_count -ge $PROCESS_COUNT_THRESHOLD ]
	then
		printf "<TR><TD align=center bgcolor=red>$user_count</TD><TD align=center bgcolor=red>$user_id</TD></TR>\n" 
		lRC=`expr $lRC + 1`
	else
		printf "<TR><TD align=center bgcolor=ivory>$user_count</TD><TD align=center bgcolor=ivory>$user_id</TD></TR>\n" 
	fi

	if [ $user_count -le $PROCESS_SHOW_THRESHOLD ]
	then
		echo "</TABLE>"
		echo "</TBODY>"

		rm $OUTFILE
		rm $TMPFILE

                if [ $lRC -gt 0 ]; then
                  echo "NUMBER OF PROCESSES " >> "/tmp/subject_issues"
                fi

		exit $lRC
	fi
done

echo "</TABLE>"
echo "</TBODY>"

rm $OUTFILE
rm $TMPFILE

if [ $lRC -gt 0 ]; then
   echo "NUMBER OF PROCESSES " >> "/tmp/subject_issues"
fi

exit $lRC
}

