#! /usr/bin/perl 

if ( $ARGV[0] eq "" ) {
	print  $0 . " {file output of ab-key show}\n";
	exit 1;
}

use Time::Local;

require 'ctime.pl';

# $ENV{'AB_HOME'}='/opt/abinitio';
# 
# $ENV{'PATH'}='/opt/abinitio/bin:$ENV{PATH}';

# @key_out=`ab-key show`;

@key_out=`cat $ARGV[0]`;

$MIN_EXPIRES=9999999999;

for ($i = 0; $i <= $#key_out; $i++) {
	# print "line " . $i . " " . $key_out[$i];
	if ( $key_out[$i] =~ /\(expires/ )  {
		@a=split(/\(expires/, $key_out[$i]);
		@b=split(/\)/, $a[1]);
		@c=split(/ /, $b[0]);
		@d=split(/\-/, $c[1]);
		$EXPIRES = timelocal(0, 0, 0, $d[2], $d[1]-1, $d[0]);
		if ( $MIN_EXPIRES > $EXPIRES ) {
	 		$MIN_EXPIRES=$EXPIRES;
		}
		# print "when " . $d[0] . $d[1] . $d[2] . " EXPIRES " . $EXPIRES . " MIN_EXPIRES " . $MIN_EXPIRES . "\n";
	}

	# print "what is in @a " . $a[1] . "\n";
} 

# $EXPIRES = timelocal(0, 0, 0, $d[2], $d[1], $d[0]);

$TIME=time();

# print "TIME " . $TIME . " MIN_EXPIRES " . $MIN_EXPIRES . "\n";;

if ( $MIN_EXPIRES != 9999999999 ) {
	$DAYS=int(($MIN_EXPIRES - $TIME)/3600/24);
} else {
	$DAYS = 9999999999;
}

print $DAYS . "\n";

# if ( $DAYS <= 7 ) {
# 	print "expires less than $DAYS days\n";
# } else {
# 	print "expires in $DAYS days\n";
# }

