#! /bin/sh

# set -x

PROG=`basename $0`
PROGDIR=`dirname $0`

. ~/.bashrc
. $PROGDIR/$PROG.env

NOW=`date '+%Y%m%d_%H%M%S'`
DOW=`date '+%w'`
LOGFILE=/tmp/$PROG.$NOW.out

ab-key show > $LOGFILE

DAYS=`$PROGDIR/check_ai_license_sub $LOGFILE`

echo $DAYS

if [ "$DAYS" -eq 9999999999 ]
then
	SUBJECT="Ab Initio License is non-expiring : `uname -n | cut -d. -f1`"
else
	SUBJECT="Ab Initio License Expires in $DAYS days : `uname -n | cut -d. -f1`"
fi

if [ "$DAYS" -gt $TD7DAYS ] && [ "$DAYS" -lt $TDREPORT ]
then
	/usr/lib/sendmail -t -v <<-!END! > /dev/null 2>&1 
	From: $FROM 
	To: $TO_G_14
	Subject: $SUBJECT
	Return-Path: $FROM
	Content-Type: text/html; charset=us-ascii

	`cat $LOGFILE | sed 's/^/<BR>/'`
	<BR>
	`ab-computer-info | sed -e 's/</\&lt;/g' -e 's/^/<BR>/'`
	<BR>
	$SIGNATURE
	.
	!END!
	rm -f $LOGFILE
	exit 0
fi

if [ "$DAYS" -lt $TD7DAYS ]
then
	/usr/lib/sendmail -t -v <<-!END! > /dev/null 2>&1 
	From: $FROM
	To: $TO_G_14
	Subject: $SUBJECT
	Return-Path: $FROM
	Importance: high
	Priority: Urgent
	X-Priority: 1
	X-Message-Flag: Follow up
	Reply-BY: `date '+%a, %d %b, %Y %H:%M:%S'`
	Content-Type: text/html; charset=us-ascii
	
	<BR>Please send to key@abinitio.com,
	<BR>
	<BR>Please find our license keys will be expiring in less than $DAYS days and computer information below. Kindly send updated license keys to us.
	<BR>
	`cat $LOGFILE | sed 's/^/<BR>/'`
	<BR>
	`ab-computer-info | sed -e 's/</\&lt;/g' -e 's/^/<BR>/'`
	<BR>
	<BR>Thanks.
	<BR>
	$SIGNATURE
	.
	!END!
fi

rm -f $LOGFILE 
exit 0
