#!/bin/ksh

NOW=`date '+%Y%m%d_%H%M%S'`

find /*/abinitio/ab_work_dir/vnode -mtime +30  >> /tmp/cache_to_cleanup.txt
 
find /*/abinitio/ab_work_dir/host -mtime +30  >> /tmp/cache_to_cleanup.txt
 
find /*/abinitio/ab_data_dir -maxdepth 1 -mtime +7 | grep -vE "(ab_port_registry|aiw|debugger|health_check|ops|volatile)" > /tmp/cache_to_cleanup.txt

find /*/abinitio/ab_data_dir/ops/tracking -maxdepth 1 -mtime +7 >> /tmp/cache_to_cleanup.txt

find /*/abinitio/ab_data_dir/debugger -mtime +1  >> /tmp/cache_to_cleanup.txt

find /tmp -mtime +1 >> /tmp/cache_to_cleanup.txt 

find /*/abinitio/eme_backups/ -mtime +110 >> /tmp/cache_to_cleanup.txt 

gde_locations=`locate -i GDE-WATCHER | xargs ls -al | awk '{print $9}' | xargs -I {} dirname {} | sort -u`

for loc in $gde_locations
do
   find $loc -mtime +1 -name 'GDE-WATCHER*' >> /tmp/cache_to_cleanup.txt
done

find /*/abinitio/promotion_saves -mtime +90 >> /tmp/cache_to_cleanup.txt
find /*/abinitio/apps -name "*sand.replaced*" -mtime +14  >> /tmp/cache_to_cleanup.txt
sort -u /tmp/cache_to_cleanup.txt > /tmp/cache_to_cleanup_${NOW}.txt

rm -f /tmp/cache_to_cleanup.txt

cat /tmp/cache_to_cleanup_${NOW}.txt | xargs rm -fR
